apiVersion: v1
kind: Secret
metadata:
  name: overdue-prometheus-watchdog
type: Opaque
stringData:
  OVERDUE__AUTH_TOKEN: replace-me-with-at-least-32-printable-ascii-characters # openssl rand -hex 32
  OVERDUE__WEBHOOK_OPS_URL: https://hooks.slack.com/services/replace/me
  OVERDUE__EMAIL_OPS_SMTP_USER: replace-me
  OVERDUE__EMAIL_OPS_SMTP_PASS: replace-me
